### ISSUE TITLE
[BUG] Deleting components sometimes causes an error which renders the workflow unusable

### ISSUE THREAD

**Issue by jlsachse** [hetida/hetida-designer#6] opened 2021-07-08 13:52 UTC
### Description
Deleting components sometimes causes an error which renders the workflow unusable.
Screenshot 1 shows an example workflow that breaks as soon as the "Train Test Split"  component (red border) is being deleted.
Afterward, the workflow can't be used anymore and the message "_An error occurred._" is shown on the UI.

### Screen Shot
![image](https://user-images.githubusercontent.com/45663021/124933481-37777a00-e004-11eb-8bd8-21abfcd8316b.png)

### Expected Behaviour
The component should be deleted and the workflow should still be usable.

### Actual Behaviour
The component is being deleted and the workflow breaks.

### Debug Information
No error logs were found in all docker containers.
Chromes console displayed the following error:
![image](https://user-images.githubusercontent.com/45663021/124932874-b7511480-e003-11eb-8fa3-c9592aa2a37c.png)

### Further Information
Hetida version: 0.6.10

**Comment by stewit** [comment] 2021-07-08 15:33
Hello, what exactly do you mean by "deleting"? 

Do you mean deprecating the (released) component?
![image](https://user-images.githubusercontent.com/16646123/124949969-4e24cd80-e012-11eb-906e-51e4286e6fa9.png)

Or do you mean removing the component instance from the workflow?

**Comment by jlsachse** [comment] 2021-07-08 19:44
Hello, I mean removing the component instance from the workflow. I can't do anything (e. g. adding component instances, connecting them) afterwards. It keeps showing the error message.

**Comment by stewit** [comment] 2021-08-11 08:25
Hello again, sorry for the long delay. In the meantime I tried to reproduce the bug but was not able to do so without further details.
If you still have the broken workflow available, please
* open the developer tools in your browser (F12 in Firefox)
* switch to the network traffic tab
* then open the workflow
* copy the response of the request that pops up and paste it here
Thank you in advance!

**Comment by stewit** [comment] 2021-09-17 11:46
Update: This bug has now been independently confirmed by 3 different users on medium-complex custom workflows. We have a workflow which allows to reproduce this bug on our internal test system now. 

Best guess is that the backend does not clean up workflow links when an operator is removed (response of PUT request seems to be invalid).

**Comment by stewit** [comment] 2021-10-13 11:28
Fix released in 0.6.15.

**Closed as completed by stewit** 2021-10-13 11:28 UTC
